### ISSUE TITLE
Annual Occupancy Estimation

### ISSUE THREAD

**Issue by Jordan-Heiman** [mfidino/autoOcc#3]
Is there a way to pull out an annual occupancy estimate with models created from `auto_occ`? Or would it be possible to add that in?

**Comment by mfidino** [comment]
What do you mean about annual estimates? If you are using data across years you could add a categorical year term into the model and then make predictions based on that.

**Comment by Jordan-Heiman** [comment]
That could work. I am just trying to be able to calculate a trend in occupancy but may end up using something from `spoccupancy` instead

**Comment by mfidino** [comment]
The model itself won’t do trends unless you incorporate that into the linear predictor. For example, if you just include a spatial covariate you make the assumption that there is no temporal variation save for the influence a species may have if they were present in the previous timestep.

the autoOcc vignette shows how to add temporal covariates, and as such I’m marking this as closed.
